name: randomsky
favicon: null
layout_spectrum: 0.8563460565637797
typography_spectrum: 0.8849664498120546
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.13631761306896806
  lightness: 0.8544064394664019
  saturation: 0.880936163244769
  rhythmicContrast: 0.5051697313319892
purpose: []
