name: randomsky
favicon: null
layout_spectrum: 0
typography_spectrum: 0.40693
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#86bd3d'
    - '#ffffff'
    - '#ffd038'
    - '#234c52'
    - '#65942c'
  brandStrength: 0.13631761306896806
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
